# Generated by Django 2.2 on 2023-09-20 10:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dfm_General_Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dfm_item_item_no', models.IntegerField(verbose_name='Item No')),
                ('dfm_assembly_level', models.CharField(blank=True, choices=[('Finished goods', 'Finished goods'), ('Rework in sub-assy design', 'Rework in sub-assy design'), ('General in sub-assy design', 'General in sub-assy design'), ('Sub-assy  Hinge uP unit', 'Sub-assy  Hinge uP unit'), ('Sub-assy  base unit', 'Sub-assy  base unit'), ('New finding', 'New finding')], default='', max_length=100, null=True, verbose_name='Assembly Level')),
                ('dfm_item_desc', models.TextField(default='', verbose_name='Item Descriptions')),
                ('dfm_item_priority', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (0, 0)], verbose_name='Priority')),
                ('dfm_item_attributes', models.CharField(blank=True, default='General', max_length=20, null=True, verbose_name='Item Type')),
                ('dfm_item_version', models.CharField(blank=True, default='Ver:2.0', max_length=20, null=True, verbose_name='Template Version')),
                ('dfm_item_notes', models.TextField(blank=True, max_length=200, null=True, verbose_name='Change Notes')),
                ('crate_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Create Date')),
            ],
            options={
                'verbose_name': 'Dfm Guidance',
                'verbose_name_plural': 'Dfm Guidance',
                'db_table': 'datacube_dfm_general_checklist',
            },
        ),
        migrations.CreateModel(
            name='Dfm_Review_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dfm_review_item_no', models.IntegerField(verbose_name='Item No')),
                ('dfm_product_nud', models.CharField(blank=True, choices=[('...', '...'), ('New', 'New'), ('Unique', 'Unique'), ('Difficult', 'Difficult')], default='...', max_length=15, null=True, verbose_name='NUD')),
                ('dfm_product_part_category', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Parts/Portion(Where)')),
                ('dfm_product_issue_symptom', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Issue Symptom')),
                ('dfm_product_design_structures', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Design structures of issues')),
                ('dfm_product_nonmacth_item', models.TextField(blank=True, default='', null=True, verbose_name='Non-match Item')),
                ('dfm_product_odm_actions', models.TextField(blank=True, default='', null=True, verbose_name='ODM  Corrective Action')),
                ('dfm_product_solution_category', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Types of solutions')),
                ('dfm_product_cnc', models.CharField(blank=True, default='...', max_length=10, null=True, verbose_name='CNC')),
                ('dfm_product_si', models.CharField(blank=True, default='...', max_length=10, null=True, verbose_name='SI')),
                ('dfm_product_pv', models.CharField(blank=True, default='...', max_length=10, null=True, verbose_name='PV')),
                ('dfm_product_mv', models.CharField(blank=True, default='...', max_length=10, null=True, verbose_name='MV')),
                ('create_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Create Date')),
                ('dfm_product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.Products', verbose_name='Product')),
                ('dfm_review_item_desc', models.ForeignKey(default='', max_length=500, on_delete=django.db.models.deletion.CASCADE, to='dfm.Dfm_General_Checklist', verbose_name='Item Descriptions')),
            ],
            options={
                'verbose_name': 'Reviewed item',
                'verbose_name_plural': 'Reviewed item',
                'db_table': 'datacube_dfm_review_result',
            },
        ),
        migrations.CreateModel(
            name='DFM_Report_Import_Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_product_name', models.CharField(help_text='Product Name', max_length=30, verbose_name='Product Name')),
                ('import_stage_cnc', models.CharField(blank=True, help_text='CNC', max_length=30, null=True, verbose_name='CNC')),
                ('import_stage_si', models.CharField(blank=True, help_text='SI', max_length=30, null=True, verbose_name='SI')),
                ('import_stage_pv', models.CharField(blank=True, help_text='PV', max_length=30, null=True, verbose_name='PV')),
                ('import_stage_mv', models.CharField(blank=True, help_text='MV', max_length=30, null=True, verbose_name='MV')),
                ('import_date', models.DateTimeField(default=datetime.datetime.now, help_text='Date', verbose_name='Update Date')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'upload record',
                'verbose_name_plural': 'upload record',
                'db_table': 'datacube_dfm_import_records',
            },
        ),
    ]
