# Generated by Django 2.2 on 2023-09-20 10:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ICs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ic_Cycle', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cycle')),
                ('ic_Project_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Project name')),
                ('ic_HW_PM', models.CharField(blank=True, max_length=50, null=True, verbose_name='HW PM')),
                ('ic_ODM', models.CharField(blank=True, max_length=30, null=True, verbose_name='ODM')),
                ('ic_Segment', models.CharField(blank=True, choices=[('OMEN', 'OMEN'), ('Victus', 'Victus'), ('Spectre', 'Spectre'), ('Envy', 'Envy'), ('GTK', 'GTK'), ('Pavilion', 'Pavilion'), ('OPP', 'OPP'), ('Chromebook', 'Chromebook')], max_length=30, null=True, verbose_name='Segment')),
                ('ic_Chipset_Type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Chipset Type')),
                ('ic_Phase', models.CharField(blank=True, choices=[('POR', 'POR'), ('PV Exit', 'PV Exit')], max_length=30, null=True, verbose_name='Phase')),
                ('ic_IC_Function', models.CharField(max_length=50, null=True, verbose_name='IC Function')),
                ('ic_Vendor', models.CharField(max_length=30, null=True, verbose_name='Vendor')),
                ('ic_Vendor_PN', models.CharField(max_length=100, null=True, verbose_name='Vendor PN')),
                ('ic_Description', models.TextField(max_length=100, null=True, verbose_name='Description')),
                ('ic_Part_Owner', models.CharField(blank=True, choices=[('OTK', 'OTK'), ('GTK', 'GTK'), ('BS', 'BS')], max_length=30, null=True, verbose_name='Part Owner')),
                ('ic_HP_PN', models.CharField(blank=True, max_length=30, null=True, verbose_name='HP PN')),
                ('ic_IC_qty', models.IntegerField(blank=True, null=True, verbose_name="IC Q'ty")),
                ('ic_Full_Feature', models.CharField(blank=True, max_length=30, null=True, verbose_name='Full Feature')),
                ('ic_Defeature', models.CharField(blank=True, max_length=30, null=True, verbose_name='Defeature')),
                ('ic_Vendor_2nd', models.CharField(blank=True, max_length=30, null=True, verbose_name='Vendor_2nd')),
                ('ic_Vendor_PN_2nd', models.CharField(blank=True, max_length=30, null=True, verbose_name='Vendor PN_2nd')),
                ('ic_Vendor_3rd', models.CharField(blank=True, max_length=30, null=True, verbose_name='Vendor_3rd')),
                ('ic_Vendor_PN_3rd', models.CharField(blank=True, max_length=30, null=True, verbose_name='Vendor PN_3rd')),
                ('ic_Vendor_4th', models.CharField(blank=True, max_length=30, null=True, verbose_name='Vendor_4th')),
                ('ic_Vendor_PN_4th', models.CharField(blank=True, max_length=30, null=True, verbose_name='Vendor PN_4th')),
                ('ic_cratedate', models.DateTimeField(default=datetime.datetime.now, verbose_name='Create Date')),
            ],
            options={
                'verbose_name': 'Critical IC',
                'verbose_name_plural': 'Critical IC',
                'db_table': 'datacube_critical_ic',
            },
        ),
        migrations.CreateModel(
            name='IC_Report_Import_Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_Project_name', models.CharField(help_text='Project name', max_length=50, null=True, verbose_name='Project name')),
                ('import_Cycle', models.CharField(help_text='Cycle', max_length=50, null=True, verbose_name='Cycle')),
                ('import_date', models.DateTimeField(default=datetime.datetime.now, help_text='Date', verbose_name='Update Date')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'IC_DataImportRecords',
                'verbose_name_plural': 'IC_DataImportRecords',
                'db_table': 'datacube_ic_import_records',
            },
        ),
    ]
