# Generated by Django 2.2 on 2023-09-20 10:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dfa_Review_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dfa_object', models.CharField(max_length=100, null=True, verbose_name='Item')),
                ('dfa_category', models.CharField(choices=[('Bonding', 'Bonding'), ('Gluing', 'Gluing'), ('Assembly', 'Assembly'), ('Screwing', 'Screwing'), ('Cables Assembly', 'Cables Assembly'), ('Material Scan & link', 'Material Scan & link'), ('Audits', 'Audits'), ('Test', 'Test'), ('Labeling & Packing', 'Labeling & Packing')], max_length=50, null=True, verbose_name='Category')),
                ('dfa_estimated_hc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Est. HC')),
                ('dfa_production_line', models.CharField(blank=True, choices=[('FA', 'FA'), ('SA', 'SA'), ('N/D', 'N/D')], max_length=5, null=True, verbose_name='Product line type')),
                ('dfa_cnc', models.CharField(blank=True, choices=[('N', 'N'), ('Y', 'Y'), ('N/A', 'N/A'), ('N/D', 'N/D')], max_length=5, null=True, verbose_name='CNC')),
                ('dfa_si_pv', models.CharField(blank=True, choices=[('N', 'N'), ('Y', 'Y'), ('N/A', 'N/A'), ('N/D', 'N/D')], max_length=5, null=True, verbose_name='SI-PV')),
                ('dfa_mv_mp', models.CharField(blank=True, choices=[('N', 'N'), ('Y', 'Y'), ('N/A', 'N/A'), ('N/D', 'N/D')], max_length=5, null=True, verbose_name='MV-MP')),
                ('dfa_HP_commodities_design', models.CharField(blank=True, choices=[('IMPACT', 'IMPACT')], max_length=10, null=True, verbose_name='CMDT_design_HP')),
                ('dfa_odm_product_designs', models.CharField(blank=True, choices=[('IMPACT', 'IMPACT')], max_length=10, null=True, verbose_name='Product_design_ODM')),
                ('dfa_odm_packing_designs_kitting_box_design', models.CharField(blank=True, choices=[('IMPACT', 'IMPACT')], max_length=10, null=True, verbose_name='PACK_BOX_design_ODM')),
                ('dfa_HP_packing_designs', models.CharField(blank=True, choices=[('IMPACT', 'IMPACT')], max_length=10, null=True, verbose_name='PACK_design_HP')),
                ('dfa_equipment_facilites_UPH_concerns', models.CharField(blank=True, choices=[('IMPACT', 'IMPACT')], max_length=10, null=True, verbose_name='EQT/FAC/UPH concern')),
                ('dfa_non_match_reason_cnc', models.CharField(blank=True, max_length=50, null=True, verbose_name='NMR_CNC')),
                ('dfa_non_match_reason_si', models.CharField(blank=True, max_length=50, null=True, verbose_name='NMR_SI')),
                ('dfa_non_match_reason_si2', models.CharField(blank=True, max_length=50, null=True, verbose_name='NMR_SI2')),
                ('dfa_non_match_reason_pv', models.CharField(blank=True, max_length=50, null=True, verbose_name='NMR_PV')),
                ('dfa_odm_corrective_action_cnc', models.CharField(blank=True, max_length=50, null=True, verbose_name='ODM_CA_CNC')),
                ('dfa_odm_corrective_action_si', models.CharField(blank=True, max_length=50, null=True, verbose_name='ODM_CA_SI')),
                ('dfa_odm_corrective_action_si2', models.CharField(blank=True, max_length=50, null=True, verbose_name='ODM_CA_SI2')),
                ('dfa_odm_corrective_action_pv', models.CharField(blank=True, max_length=50, null=True, verbose_name='ODM_CA_PV')),
                ('dfa_pictures_from_factory', models.CharField(blank=True, choices=[('Y', 'Y')], max_length=5, null=True, verbose_name='PIC')),
                ('dfa_HP_internal_discussion', models.CharField(blank=True, max_length=50, null=True, verbose_name='INTL_CMT_HP')),
                ('dfa_HP_internal_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N')], max_length=5, null=True, verbose_name='INTL_ASS_HP')),
                ('dfa_crate_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='CreateDate')),
                ('dfa_product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.Products', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Reviewed item',
                'verbose_name_plural': 'Reviewed item',
                'db_table': 'datacube_dfa_result',
            },
        ),
        migrations.CreateModel(
            name='Dfa_Report_Import_Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_product_name', models.CharField(max_length=30, verbose_name='Product Name')),
                ('import_odm', models.CharField(max_length=30, verbose_name='ODM')),
                ('import_date', models.DateTimeField(default=datetime.datetime.now, help_text='Date', verbose_name='Update Date')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'upload record',
                'verbose_name_plural': 'upload record',
                'db_table': 'datacube_dfa_import_records',
            },
        ),
    ]
