# Generated by Django 2.2 on 2023-09-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalcase',
            name='odm_name',
            field=models.CharField(choices=[('IMX', 'IMX'), ('India', 'India')], max_length=15, verbose_name='Factory'),
        ),
    ]
